services:
  # Backend API Service
  - type: web
    name: deepfake-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://WaizKayani:Ishfaq4399@deepfakedetection.emo9lif.mongodb.net/deepfake_detection?retryWrites=true&w=majority&appName=DeepfakeDetection
      - key: DATABASE_NAME
        value: deepfake_detection
      - key: API_HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://deepfake-frontend-fh35.onrender.com,https://deepfake-frontend.onrender.com,http://localhost:3000,http://127.0.0.1:3000
      - key: MAX_FILE_SIZE
        value: 104857600
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MODEL_CACHE_DIR
        value: ./ml_models
      - key: HUGGINGFACE_CACHE_DIR
        value: ./cache

  # Frontend Service
  - type: web
    name: deepfake-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://deepfake-detection-and-media.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production 